package replicalead;

/**
* CoreGameServerIDL/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/warrenwhite/eclipse-workspace/COMP-6231-A2/src/GameServer.idl
* Friday, June 19, 2020 9:25:27 PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public replicalead.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (replicalead.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = replicalead.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    replicalead.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return replicalead.GameServerHelper.type ();
  }

}
