package replicatwo;

/**
* replicatwo/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, August 6, 2020 5:17:52 PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public replicatwo.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (replicatwo.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = replicatwo.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    replicatwo.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return replicatwo.GameServerHelper.type ();
  }

}
