package replicatwo;


/**
 * replicatwo/GameServerPOA.java . Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from GameServer.idl Thursday, August 6, 2020 5:17:52 PM EDT
 */

public abstract class GameServerPOA extends org.omg.PortableServer.Servant
    implements replicatwo.GameServerOperations, org.omg.CORBA.portable.InvokeHandler {

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable();
  static {
    _methods.put("createPlayerAccount", new java.lang.Integer(0));
    _methods.put("playerSignIn", new java.lang.Integer(1));
    _methods.put("playerSignOut", new java.lang.Integer(2));
    _methods.put("adminSignIn", new java.lang.Integer(3));
    _methods.put("adminSignOut", new java.lang.Integer(4));
    _methods.put("getPlayerStatus", new java.lang.Integer(5));
    _methods.put("transferAccount", new java.lang.Integer(6));
    _methods.put("suspendAccount", new java.lang.Integer(7));
    _methods.put("initiateCorruption", new java.lang.Integer(8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke(String $method,
      org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler $rh) {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue()) {
      case 0: // replicatwo/GameServer/createPlayerAccount
      {
        String fName = in.read_string();
        String lName = in.read_string();
        String uName = in.read_string();
        String password = in.read_string();
        String ipAddress = in.read_string();
        int age = in.read_long();
        String $result = null;
        $result = this.createPlayerAccount(fName, lName, uName, password, ipAddress, age);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 1: // replicatwo/GameServer/playerSignIn
      {
        String uName = in.read_string();
        String password = in.read_string();
        String ipAddress = in.read_string();
        String $result = null;
        $result = this.playerSignIn(uName, password, ipAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 2: // replicatwo/GameServer/playerSignOut
      {
        String uName = in.read_string();
        String ipAddress = in.read_string();
        String $result = null;
        $result = this.playerSignOut(uName, ipAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 3: // replicatwo/GameServer/adminSignIn
      {
        String uName = in.read_string();
        String password = in.read_string();
        String ipAddress = in.read_string();
        String $result = null;
        $result = this.adminSignIn(uName, password, ipAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 4: // replicatwo/GameServer/adminSignOut
      {
        String uName = in.read_string();
        String ipAddress = in.read_string();
        String $result = null;
        $result = this.adminSignOut(uName, ipAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 5: // replicatwo/GameServer/getPlayerStatus
      {
        String uName = in.read_string();
        String password = in.read_string();
        String ipAddress = in.read_string();
        String $result = null;
        $result = this.getPlayerStatus(uName, password, ipAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 6: // replicatwo/GameServer/transferAccount
      {
        String uName = in.read_string();
        String password = in.read_string();
        String oldIpAddress = in.read_string();
        String newIpAddress = in.read_string();
        String $result = null;
        $result = this.transferAccount(uName, password, oldIpAddress, newIpAddress);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 7: // replicatwo/GameServer/suspendAccount
      {
        String uName = in.read_string();
        String password = in.read_string();
        String ipAddress = in.read_string();
        String uNameToSuspend = in.read_string();
        String $result = null;
        $result = this.suspendAccount(uName, password, ipAddress, uNameToSuspend);
        out = $rh.createReply();
        out.write_string($result);
        break;
      }

      case 8: // replicatwo/GameServer/initiateCorruption
      {
        boolean $result = false;
        $result = this.initiateCorruption();
        out = $rh.createReply();
        out.write_boolean($result);
        break;
      }

      default:
        throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {"IDL:replicatwo/GameServer:1.0"};

  public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
    return (String[]) __ids.clone();
  }

  public GameServer _this() {
    return GameServerHelper.narrow(super._this_object());
  }

  public GameServer _this(org.omg.CORBA.ORB orb) {
    return GameServerHelper.narrow(super._this_object(orb));
  }


} // class GameServerPOA
