package replicatwo;


/**
 * replicatwo/GameServer.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * GameServer.idl Thursday, August 6, 2020 5:17:52 PM EDT
 */

public interface GameServer
    extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface GameServer
