package replicatwo;


/**
 * replicatwo/GameServerOperations.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from GameServer.idl Thursday, August 6, 2020 5:17:52 PM EDT
 */

public interface GameServerOperations {
  String createPlayerAccount(String fName, String lName, String uName, String password,
      String ipAddress, int age);

  String playerSignIn(String uName, String password, String ipAddress);

  String playerSignOut(String uName, String ipAddress);

  String adminSignIn(String uName, String password, String ipAddress);

  String adminSignOut(String uName, String ipAddress);

  String getPlayerStatus(String uName, String password, String ipAddress);

  String transferAccount(String uName, String password, String oldIpAddress, String newIpAddress);

  String suspendAccount(String uName, String password, String ipAddress, String uNameToSuspend);

  boolean initiateCorruption();
} // interface GameServerOperations
