package replicaone;


/**
* replicaone/_GameServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, August 6, 2020 8:26:15 PM EDT
*/

public class _GameServerStub extends org.omg.CORBA.portable.ObjectImpl implements replicaone.GameServer
{

  public String createPlayerAccount (String fName, String lName, String uName, String password, String ipAddress, int age)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPlayerAccount", true);
                $out.write_string (fName);
                $out.write_string (lName);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (ipAddress);
                $out.write_long (age);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPlayerAccount (fName, lName, uName, password, ipAddress, age        );
            } finally {
                _releaseReply ($in);
            }
  } // createPlayerAccount

  public String playerSignIn (String uName, String password, String ipAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("playerSignIn", true);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (ipAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return playerSignIn (uName, password, ipAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // playerSignIn

  public String playerSignOut (String uName, String ipAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("playerSignOut", true);
                $out.write_string (uName);
                $out.write_string (ipAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return playerSignOut (uName, ipAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // playerSignOut

  public String adminSignIn (String uName, String password, String ipAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adminSignIn", true);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (ipAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return adminSignIn (uName, password, ipAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // adminSignIn

  public String adminSignOut (String uName, String ipAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adminSignOut", true);
                $out.write_string (uName);
                $out.write_string (ipAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return adminSignOut (uName, ipAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // adminSignOut

  public String getPlayerStatus (String uName, String password, String ipAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayerStatus", true);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (ipAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayerStatus (uName, password, ipAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayerStatus

  public String transferAccount (String uName, String password, String oldIpAddress, String newIpAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("transferAccount", true);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (oldIpAddress);
                $out.write_string (newIpAddress);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return transferAccount (uName, password, oldIpAddress, newIpAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // transferAccount

  public String suspendAccount (String uName, String password, String ipAddress, String uNameToSuspend)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("suspendAccount", true);
                $out.write_string (uName);
                $out.write_string (password);
                $out.write_string (ipAddress);
                $out.write_string (uNameToSuspend);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return suspendAccount (uName, password, ipAddress, uNameToSuspend        );
            } finally {
                _releaseReply ($in);
            }
  } // suspendAccount

  public boolean initiateCorruption ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("initiateCorruption", true);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return initiateCorruption (        );
            } finally {
                _releaseReply ($in);
            }
  } // initiateCorruption

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:replicaone/GameServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServerStub
