package replicaone;


/**
* CoreGameServerIDL/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/warrenwhite/eclipse-workspace/COMP-6231-A2/src/GameServer.idl
* Friday, June 19, 2020 9:25:27 PM EDT
*/

public interface GameServerOperations 
{
  String createPlayerAccount (String fName, String lName, String uName, String password, String ipAddress, int age);
  String playerSignIn (String uName, String password, String ipAddress);
  String playerSignOut (String uName, String ipAddress);
  String adminSignIn (String uName, String password, String ipAddress);
  String adminSignOut (String uName, String ipAddress);
  String getPlayerStatus (String uName, String password, String ipAddress);
  String transferAccount (String uName, String password, String oldIpAddress, String newIpAddress);
  String suspendAccount (String uName, String password, String ipAddress, String uNameToSuspend);
} // interface GameServerOperations
