package replicaone;

/**
* replicaone/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, August 6, 2020 8:26:15 PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public replicaone.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (replicaone.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = replicaone.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    replicaone.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return replicaone.GameServerHelper.type ();
  }

}
