package replicaone;


/**
 * replicaone/GameServerHelper.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from GameServer.idl Thursday, August 6, 2020 8:26:15 PM EDT
 */

abstract public class GameServerHelper {
  private static String _id = "IDL:replicaone/GameServer:1.0";

  public static void insert(org.omg.CORBA.Any a, replicaone.GameServer that) {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
    a.type(type());
    write(out, that);
    a.read_value(out.create_input_stream(), type());
  }

  public static replicaone.GameServer extract(org.omg.CORBA.Any a) {
    return read(a.create_input_stream());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;

  synchronized public static org.omg.CORBA.TypeCode type() {
    if (__typeCode == null) {
      __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(replicaone.GameServerHelper.id(),
          "GameServer");
    }
    return __typeCode;
  }

  public static String id() {
    return _id;
  }

  public static replicaone.GameServer read(org.omg.CORBA.portable.InputStream istream) {
    return narrow(istream.read_Object(_GameServerStub.class));
  }

  public static void write(org.omg.CORBA.portable.OutputStream ostream,
      replicaone.GameServer value) {
    ostream.write_Object((org.omg.CORBA.Object) value);
  }

  public static replicaone.GameServer narrow(org.omg.CORBA.Object obj) {
    if (obj == null)
      return null;
    else if (obj instanceof replicaone.GameServer)
      return (replicaone.GameServer) obj;
    else if (!obj._is_a(id()))
      throw new org.omg.CORBA.BAD_PARAM();
    else {
      org.omg.CORBA.portable.Delegate delegate =
          ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
      replicaone._GameServerStub stub = new replicaone._GameServerStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static replicaone.GameServer unchecked_narrow(org.omg.CORBA.Object obj) {
    if (obj == null)
      return null;
    else if (obj instanceof replicaone.GameServer)
      return (replicaone.GameServer) obj;
    else {
      org.omg.CORBA.portable.Delegate delegate =
          ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
      replicaone._GameServerStub stub = new replicaone._GameServerStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
