package replicaone;


/**
 * replicaone/GameServer.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * GameServer.idl Thursday, August 6, 2020 8:26:15 PM EDT
 */

public interface GameServer
    extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface GameServer
